### ISSUE TITLE
Crashes on empty pipe

### ISSUE THREAD

**Issue by djibarian** [whs/piped-webpack#3]
If `gulp-changed` results in an empty pipe the plugin crashes.

I recently replaced it from `webpack-stream` due to the `DllPlugin` glitch. The latest in this situation was showing a message informing that webpack would not run because of an empty entry, but this plugin crashes instead telling `WebpackOptionsValidationError: Invalid configuration object. ...`.

**Comment by whs** [comment]
Thanks for your bug report. Version 1.3.1 has been released to npm.

If your use case is to watch for changed file, I recommend to use webpack's [watch system](https://github.com/whs/piped-webpack#watching) instead. It should be way faster than running the gulp task again as it can reuse compilation cache.

**Comment by djibarian** [comment]
I know about watch, but optionally I need to include webpack as a gulp task among others. Thanks for the quick fix.
