### ISSUE TITLE
Watch mode emitting ALL components

### ISSUE THREAD

**Issue by djibarian** [whs/piped-webpack#4]
I’m using this webpack config to test the issue:

```
{
    watch: true,
    entry: {
        react1: ['./src/components/react1.jsx'],
        react2: ['./src/components/react2.jsx']
    },
    output: {
        filename: 'components/[name].js',
        path: path.resolve(__dirname, 'build-dev')
    },
    module: {
        loaders: [
            { test: /\.jsx$/, loader: 'babel-loader' }
        ]
    },
    plugins: [
        new webpack.DllReferencePlugin({
            manifest: path.join('build-dev', 'components/common-manifest.json')
        })
    ]
}
```

This works fine when run with `webpack --watch` (only changed modules are emitted, and you must actually change the file, i.e. saving it with no changes doesn’t fire webpack). But using the same config with gulp ALL the components are always emitted.

This is the gulp code:

```
return gulp.src([])
    .pipe(pipedWebpack(<config here>))
    .pipe(gulp.dest(config.dst))
```

**Comment by tnuanchuay** [comment]
I'm not pro-webpack but I think you shouldn't have entry list in config file.
PipedWebpack should send you which entry we want to process.

```
{
    watch: true,
    output: {
        filename: 'components/[name].js',
        path: path.resolve(__dirname, 'build-dev')
    },
    module: {
        loaders: [
            { test: /\.jsx$/, loader: 'babel-loader' }
        ]
    },
    plugins: [
        new webpack.DllReferencePlugin({
            manifest: path.join('build-dev', 'components/common-manifest.json')
        })
    ]
}
```

try with this config

**Comment by djibarian** [comment]
Well both ways are correct. You can keep `entry` empty and use `gulp.src` to fill it in, or as in the example, you can keep `gulp.src` empty and include `entry` in the webpack config. Either way ALL files are recompiled in watch mode.

**Comment by whs** [comment]
We are supporting both supplying entrypoints to this module, and without.

Are you using gulp.watch? I don't recommend running this module with that, and instead using normal gulp.task.

In my codebase, after saving a file with no change the recompilation only took 36ms as compared to 15s in new compilation. Even if it might not be as fast as webpack --watch (which I haven't check whether it recompile on empty change -- the behavior might be depending on how my editor save the file), it is blazingly fast already and I don't think worth optimizing for.

**Comment by djibarian** [comment]
I’m not using `gulp.watch`, I’m using `gulp.task`.

You’re right on the time to recompile. After a change to one of the files the compile time goes down to some ms, but the problem is not that. The problem is that all the files are always emitted.

I have chained another task after `gulp.dest` to send the changed files over FTP and because all the files are changed, all the files are sent over, and that is unnecessary and very time consuming. That’s the reason I need only changed files to be emitted and passed through the stream.

**Comment by whs** [comment]
This should be fixed in e6f42d8, but there's a but for your use case.

What we did is exactly the same as what webpack did (recompile even if you save with no change). However, webpack --watch will remember the last stats hash and skip printing stats if the hash is the same. In that commit I've added the same check and it shouldn't print stats or emit any file if all contents are the same.

However, in your use case I think there is another complex issue to sort: sending out only changed files. We don't have information on which files are changed and so we always dump the entire memory-fs-stream into the output stream every time.

**Comment by djibarian** [comment]
I think you are doing something in a different way than webpack. Please look at this output:

```
[12:39:29] Webpack is watching
[12:39:31] Hash: 048061790961c76849fc
Version: webpack 3.6.0
Time: 1081ms
            Asset     Size  Chunks                    Chunk Names
assets/image1.jpg   902 kB          [emitted]  [big]  
    app/react2.js  24.3 kB       0  [emitted]         react2
    app/react1.js  3.46 kB       1  [emitted]         react1
   [0] external "common_lib" 42 bytes {0} {1} [not cacheable]
   [1] delegated ./node_modules/react/index.js from dll-reference common_lib 42 bytes {0} {1} [built]
   [2] delegated ./node_modules/react-dom/index.js from dll-reference common_lib 42 bytes {0} {1} [built]
   [3] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
   [4] ./node_modules/style-loader/lib/addStyles.js 9.41 kB {0} [built]
   [5] multi ./src/containers/react1.jsx 28 bytes {1} [built]
   [6] ./src/containers/react1.jsx 490 bytes {1} [built]
   [7] multi ./src/containers/react2.jsx 28 bytes {0} [built]
   [8] ./src/containers/react2.jsx 3.58 kB {0} [built]
   [9] ./src/styles/base.scss 1.16 kB {0} [built]
  [10] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/styles/base.scss 226 bytes {0} [built]
  [11] ./node_modules/style-loader/lib/urls.js 3.01 kB {0} [built]
  [12] ./src/containers/react2.scss 1.16 kB {0} [built]
  [13] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/containers/react2.scss 247 bytes {0} [built]
  [14] ./src/assets/image1.jpg 63 bytes {0} [built]
[12:39:31] gulp-debug: assets/image1.jpg
[12:39:31] gulp-debug: app/react2.js
[12:39:31] gulp-debug: app/react1.js

```

Here `react1`, `react2` and `image1` are emitted, that is, all files in the build. Because this is a first build, time is 1081ms. Making any change to any of the files will build everything again and the output will be the same. The only difference will be that time will go down drastically as you mentioned.

Now look at this output:

```
Hash: 4a86dd6fd766b994f6f7
Version: webpack 3.6.0
Time: 103ms
        Asset     Size  Chunks             Chunk Names
app/react2.js  24.3 kB       0  [emitted]  react2
 + 2 hidden assets
   [1] delegated ./node_modules/react/index.js from dll-reference common_lib 42 bytes {0} {1} [built]
   [2] delegated ./node_modules/react-dom/index.js from dll-reference common_lib 42 bytes {0} {1} [built]
   [8] ./src/containers/react2.jsx 3.59 kB {0} [built]
    + 12 hidden modules

```

Here webpack is called directly, also in watch mode. This is the output after changing `react2`. As you can see, only `react2` is emitted, and you actually need to change the file, I mean, saving the file with no changes doesn’t fire any build.

Furthermore, looking at the files timestamps on `app`, only `react2` was changed, so your assertion about all files being emitted but only those changed logged doesn’t seem to be true.

So, based in your previous comments, I’ve piped `gulp-changed` to the output stream to avoid copying and thus FTP uploading unchanged files. This seems to be working very well, but anyway webpack output in watch mode is way nicer than yours and definitely not the same. Actually, it looks more like a complete rebuild than an incremental build. Final task looks like this:

```
    return gulp.src(path.join(config.src, 'containers/*.jsx'))
        .pipe(pipedWebpack({
            watch: true,
            ...
        }))
        .pipe(changed(config.dst, { hasChanged: changed.compareContents }))
        .pipe(gulp.dest(config.dst))
        .pipe(remote.dest(config.remote.root));

```

Hope it helps.

**Comment by whs** [comment]
I've ported webpack's output formatting option.

Please test 621067f whether the output is what you are expecting.

**Comment by djibarian** [comment]
Output is exactly as if executed externally now. Many thanks!

**Comment by whs** [comment]
Version 1.4.0 has been released on npm :tada:
